export CUDA_VISIBLE_DEVICES=1

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path jy_without_crtm.csv --model_id JY_96_96_jy_without_crtm --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 139 --dec_in 139 --c_out 139 --des 'Exp' --itr 1 --train_epochs 2
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path jy_original_without_crtn_delete_ot_0.csv --model_id jy_original_without_crtn_delete_ot_0 --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 139 --dec_in 139 --c_out 139 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 2_jy_mean_without_ot_0.csv --model_id JY_96_96_2_jy_mean_without_ot_0 --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 3_jy_median_without_ot_0.csv --model_id JY_96_96_3_jy_median_without_ot_0 --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_jy_original_without_crtn_delete_ot_0.csv --model_id JY_96_96_3_1_jy_original_without_crtn_delete_ot_0 --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 4_jy_weight_without_ot_0.csv --model_id JY_96_96_4_jy_weight_without_ot_0 --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 2
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 5_jy_time_embedding_without_weight.csv --model_id JY_96_96_5_jy_time_embedding_without_weight --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 146 --dec_in 146 --c_out 146 --des 'Exp' --itr 1 --train_epochs 2
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 6_jy_time_embedding_with_weight.csv --model_id JY_96_96_6_jy_time_embedding_with_weight --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 146 --dec_in 146 --c_out 146 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 7_jy_one_hot_encoding_with_index.csv --model_id JY_96_96_7_jy_one_hot_encoding_with_index --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 545 --dec_in 545 --c_out 545 --des 'Exp' --itr 1 --train_epochs 2
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 8_jy_shortest_lead_hr.csv --model_id JY_96_96_8_jy_shortest_lead_hr --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 137 --dec_in 137 --c_out 137 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 9_jy_scaling.csv --model_id JY_96_96_9_jy_scaling --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 2
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 10_jy_scaling_weight.csv --model_id JY_96_96_10_jy_scaling_weight --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 2

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 11_dataset_arrange_without_crtn.csv --model_id JY_96_96_11_dataset_arrange_without_crtn --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 12_dataset_arrage_with_season_last.csv --model_id JY_96_96_12_dataset_arrage_with_season_last --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 13_dataset_arrage_with_random.csv --model_id JY_96_96_13_dataset_arrage_with_random --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 14_pca_54_col.csv --model_id JY_96_96_14_pca_54_col --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 53 --dec_in 53 --c_out 53 --des 'Exp' --itr 1 --train_epochs 3
#
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 16_with_scaler_and_crtn_embbeding.csv --model_id JY_96_96_16_with_scaler_and_crtn_embbeding --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 142 --dec_in 142 --c_out 142 --des 'Exp' --itr 1 --train_epochs 3
#
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 17_with_scaler_with_weight.csv --model_id JY_96_96_17_with_scaler_with_weight --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 11_dataset_arrange_without_crtn.csv --model_id JY_96_96_11_dataset_arrange_without_crtn --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 18_with_weight_base_on_case12.csv --model_id JY_96_96_18_with_weight_base_on_case12 --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 19_with_scaler.csv --model_id JY_96_96_19_with_scaler --model Autoformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3



#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case1.csv --model_id JY_24_24_s1_case1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case2.csv --model_id JY_24_24_s1_case2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case3.csv --model_id JY_24_24_s1_case3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3



#s2_case1_from_s1_case
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case1_from_s1_case_1.csv --model_id JY_24_24_s2_case1_from_s1_case_1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case1_from_s1_case_2.csv --model_id JY_24_24_s2_case1_from_s1_case_2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case1_from_s1_case_3.csv --model_id JY_24_24_s2_case1_from_s1_case_3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

#s2_case2_from_s1_case
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case2_from_s1_case_1.csv --model_id JY_24_24_s2_case2_from_s1_case_1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case2_from_s1_case_2.csv --model_id JY_24_24_s2_case2_from_s1_case_2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case2_from_s1_case_3.csv --model_id JY_24_24_s2_case2_from_s1_case_3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

#s2_case3_from_s1_case
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case3_from_s1_case_1.csv --model_id JY_24_24_s2_case3_from_s1_case_1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case3_from_s1_case_2.csv --model_id JY_24_24_s2_case3_from_s1_case_2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case3_from_s1_case_3.csv --model_id JY_24_24_s2_case2_from_s1_case_3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3




python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_1.csv --model_id JY_24_24_s3_case1_from_s2_case_4_1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_2.csv --model_id JY_24_24_s3_case1_from_s2_case_4_2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_3.csv --model_id JY_24_24_s3_case1_from_s2_case_4_3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_4.csv --model_id JY_24_24_s3_case1_from_s2_case_4_4 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_5.csv --model_id JY_24_24_s3_case1_from_s2_case_4_5 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_6.csv --model_id JY_24_24_s3_case1_from_s2_case_4_6 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_7.csv --model_id JY_24_24_s3_case1_from_s2_case_4_7 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_8.csv --model_id JY_24_24_s3_case1_from_s2_case_4_8 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_9.csv --model_id JY_24_24_s3_case1_from_s2_case_4_9 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case1_with_dual_embedding.csv --model_id JY_24_24_s1_case1_with_dual_embedding --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 102 --dec_in 102 --c_out 102 --des 'Exp' --itr 1 --train_epochs 3




python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_1.csv --model_id JY_24_24_s3_case1_from_s2_case_5_1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_2.csv --model_id JY_24_24_s3_case1_from_s2_case_5_2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_3.csv --model_id JY_24_24_s3_case1_from_s2_case_5_3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_4.csv --model_id JY_24_24_s3_case1_from_s2_case_5_4 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_5.csv --model_id JY_24_24_s3_case1_from_s2_case_5_5 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_6.csv --model_id JY_24_24_s3_case1_from_s2_case_5_6 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_7.csv --model_id JY_24_24_s3_case1_from_s2_case_5_7 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_8.csv --model_id JY_24_24_s3_case1_from_s2_case_5_8 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_9.csv --model_id JY_24_24_s3_case1_from_s2_case_5_9 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3



python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_1.csv --model_id JY_24_24_s3_case1_from_s2_case_5_1 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_2.csv --model_id JY_24_24_s3_case1_from_s2_case_5_2 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_3.csv --model_id JY_24_24_s3_case1_from_s2_case_5_3 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_4.csv --model_id JY_24_24_s3_case1_from_s2_case_5_4 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_5.csv --model_id JY_24_24_s3_case1_from_s2_case_5_5 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_6.csv --model_id JY_24_24_s3_case1_from_s2_case_5_6 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_7.csv --model_id JY_24_24_s3_case1_from_s2_case_5_7 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_8.csv --model_id JY_24_24_s3_case1_from_s2_case_5_8 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_9.csv --model_id JY_24_24_s3_case1_from_s2_case_5_9 --model Autoformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
