#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path jy_without_crtm.csv --model_id JY_96_96_jy_without_crtm --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 139 --dec_in 139 --c_out 139 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path jy_original_without_crtn_delete_ot_0.csv --model_id JY_96_96_jy_original_without_crtn_delete_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 140 --dec_in 140 --c_out 140 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 2_jy_mean.csv --model_id JY_96_96_2_jy_mean --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 2_jy_mean_without_ot_0.csv --model_id JY_96_96_2_jy_mean_without_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 3_jy_median_without_ot_0.csv --model_id JY_96_96_3_jy_median_without_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 4_jy_weight_without_ot_0.csv --model_id JY_96_96_4_jy_weight_without_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_jy_original_without_crtn_delete_ot_0.csv --model_id JY_96_96_1_jy_original_without_crtn_delete_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 5_jy_time_embedding_without_weight.csv --model_id JY_96_96_5_jy_time_embedding_without_weight --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 146 --dec_in 146 --c_out 146 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_jy_original_without_crtn_delete_ot_0.csv --model_id JY_96_96_1_jy_original_without_crtn_delete_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_jy_original_without_crtn_delete_ot_0.csv --model_id JY_96_96_1_jy_original_without_crtn_delete_ot_0 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 7_jy_one_hot_encoding_with_index.csv --model_id JY_96_96_7_jy_one_hot_encoding_with_index --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 545 --dec_in 545 --c_out 545 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 8_jy_shortest_lead_hr.csv --model_id JY_96_96_8_jy_shortest_lead_hr --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 137 --dec_in 137 --c_out 137 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 9_jy_scaling.csv --model_id JY_96_96_9_jy_scaling --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 10_jy_scaling_weight.csv --model_id JY_96_96_10_jy_scaling_weight --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 11_dataset_arrange_without_crtn.csv --model_id JY_96_96_11_dataset_arrange_without_crtn --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 12_dataset_arrage_with_season_last.csv --model_id JY_96_96_12_dataset_arrage_with_season_last --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 13_dataset_arrage_with_random.csv --model_id JY_96_96_13_dataset_arrage_with_random --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 14_pca_52_sc_scaler_col.csv --model_id JY_96_96_14_pca_52_sc_scaler_col --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 52 --dec_in 52 --c_out 52 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 14_pca_70_sc_scaler_col.csv --model_id JY_96_96_14_pca_70_sc_scaler_col --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 70 --dec_in 70 --c_out 70 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 16_with_scaler_and_crtn_embbeding.csv --model_id JY_96_96_16_with_scaler_and_crtn_embbeding --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 142 --dec_in 142 --c_out 142 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 17_with_scaler_with_weight.csv --model_id JY_96_96_17_with_scaler_with_weight --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 18_with_weight_base_on_case12.csv --model_id JY_96_96_18_with_weight_base_on_case12 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 11_dataset_arrange_without_crtn.csv --model_id JY_96_96_11_dataset_arrange_without_crtn --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path crtn_1.csv --model_id JY_96_96_crtn_1 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path crtn_2.csv --model_id JY_96_96_crtn_2 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path crtn_3.csv --model_id JY_96_96_crtn_3 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path crtn_4.csv --model_id JY_96_96_crtn_4 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path crtn_5.csv --model_id JY_96_96_crtn_5 --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 19_with_scaler.csv --model_id JY_96_96_19_with_scaler --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#
#
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_data.csv --model_id JY_24_24_1_data --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_data.csv --model_id JY_48_48_1_data --model Transformer --data custom --features M --seq_len 48 --label_len 24 --pred_len 48 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 3_data.csv --model_id JY_96_96_3_data --model Transformer --data custom --features M --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 1_data.csv --model_id JY_24_24_1_data --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 2_data.csv --model_id JY_24_24_2_data --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path 3_data.csv --model_id JY_24_24_3_data --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10\
#
#
#
#
##final _2
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_8.csv --model_id final_aug_8 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_16.csv --model_id final_aug_16 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_32.csv --model_id final_aug_32 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2.csv --model_id final_aug_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 10
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2.csv --model_id final_aug_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#
#

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_1_max.csv --model_id JY_24_24_final_1_max --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_1_median.csv --model_id JY_2
## final
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_1_avg.csv --model_id JY_24_24_final_1_avg --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2.csv --model_id JY_24_24_final_aug_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2.csv --model_id JY_24_24_final_aug_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 138 --dec_in 138 --c_out 138 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v2.csv --model_id JY_24_24_final_aug_2_v2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v3.csv --model_id JY_24_24_final_aug_2_v3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v4.csv --model_id JY_24_24_final_aug_2_v4 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_1_avg_v2.csv --model_id JY_24_24_final_1_avg_v2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v5.csv --model_id JY_24_24_final_aug_2_v5 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v6.csv --model_id JY_24_24_final_aug_2_v6 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v7.csv --model_id JY_24_24_final_aug_2_v7 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v8.csv --model_id JY_24_24_final_aug_2_v8 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v9.csv --model_id JY_24_24_final_aug_2_v9 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v10.csv --model_id JY_24_24_final_aug_2_v10 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path final_aug_2_v11.csv --model_id JY_24_24_final_aug_2_v11 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3


python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case1.csv --model_id JY_24_24_s1_case1 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case2.csv --model_id JY_24_24_s1_case2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case3.csv --model_id JY_24_24_s1_case3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3


#s2_case1_from_s1_case
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case1_from_s1_case_1.csv --model_id JY_24_24_s2_case1_from_s1_case_1 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case1_from_s1_case_2.csv --model_id JY_24_24_s2_case1_from_s1_case_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case1_from_s1_case_3.csv --model_id JY_24_24_s2_case1_from_s1_case_3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

#s2_case2_from_s1_case
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case2_from_s1_case_1.csv --model_id JY_24_24_s2_case2_from_s1_case_1 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case2_from_s1_case_2.csv --model_id JY_24_24_s2_case2_from_s1_case_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case2_from_s1_case_3.csv --model_id JY_24_24_s2_case2_from_s1_case_3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

#s2_case3_from_s1_case
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case3_from_s1_case_1.csv --model_id JY_24_24_s2_case3_from_s1_case_1 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case3_from_s1_case_2.csv --model_id JY_24_24_s2_case3_from_s1_case_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s2_case3_from_s1_case_3.csv --model_id JY_24_24_s2_case3_from_s1_case_3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s1_case1_with_dual_embedding.csv --model_id JY_24_24_s1_case1_with_dual_embedding --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 102 --dec_in 102 --c_out 102 --des 'Exp' --itr 1 --train_epochs 3


python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_1.csv --model_id JY_24_24_s3_case1_from_s2_case_5_1 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_2.csv --model_id JY_24_24_s3_case1_from_s2_case_5_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_3.csv --model_id JY_24_24_s3_case1_from_s2_case_5_3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_4.csv --model_id JY_24_24_s3_case1_from_s2_case_5_4 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_5.csv --model_id JY_24_24_s3_case1_from_s2_case_5_5 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_6.csv --model_id JY_24_24_s3_case1_from_s2_case_5_6 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_7.csv --model_id JY_24_24_s3_case1_from_s2_case_5_7 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_8.csv --model_id JY_24_24_s3_case1_from_s2_case_5_8 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_5_9.csv --model_id JY_24_24_s3_case1_from_s2_case_5_9 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3



#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_1_with_PCA_0.999.csv --model_id JY_24_24_s3_case1_from_s2_case_4_1_with_PCA_0.999 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 74 --dec_in 74 --c_out 74 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_1_with_PCA_0.99.csv --model_id JY_24_24_s3_case1_from_s2_case_4_1_with_PCA_0.99 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 50 --dec_in 50 --c_out 50 --des 'Exp' --itr 1 --train_epochs 3
#python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_4_1_with_PCA_0.9.csv --model_id JY_24_24_s3_case1_from_s2_case_4_1_with_PCA_0.9 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 26 --dec_in 26 --c_out 26 --des 'Exp' --itr 1 --train_epochs 3


python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_1.csv --model_id JY_24_24_s3_case1_from_s2_case_6_1 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_2.csv --model_id JY_24_24_s3_case1_from_s2_case_6_2 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_3.csv --model_id JY_24_24_s3_case1_from_s2_case_6_3 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_4.csv --model_id JY_24_24_s3_case1_from_s2_case_6_4 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_5.csv --model_id JY_24_24_s3_case1_from_s2_case_6_5 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_6.csv --model_id JY_24_24_s3_case1_from_s2_case_6_6 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_7.csv --model_id JY_24_24_s3_case1_from_s2_case_6_7 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_8.csv --model_id JY_24_24_s3_case1_from_s2_case_6_8 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3
python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./dataset/JY/ --data_path s3_case1_from_s2_case_6_9.csv --model_id JY_24_24_s3_case1_from_s2_case_6_9 --model Transformer --data custom --features M --seq_len 24 --label_len 12 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 99 --dec_in 99 --c_out 99 --des 'Exp' --itr 1 --train_epochs 3

